### ISSUE TITLE
switching the audio device incorrectly

### ISSUE THREAD

**Issue by XiaoYue-Kun** [Jax-Core/YourMixer#1]
It seems the function of switching the audio device isn't working correctly.
In my real case, I have five audio devices(let's call them A to E). When I switched to device A, actually device B is enabled. When switching to B, C is enabled, etc. And device E can be correctly switched to, while A can never be switched to in this module.
I wonder if it's due to too many audio devices I have, but in fact I really need all of them.

**Comment by EnhancedJax** [comment]
Are you switching with the drop-down menu?

**Comment by XiaoYue-Kun** [comment]
yes.it looks like this
![屏幕截图 2022-04-02 212529](https://user-images.githubusercontent.com/95956805/161385392-b1c4ec18-e675-4998-b24f-2905966b34d3.png)

**Comment by EnhancedJax** [comment]
Seems like the devices have a different index than the context menu. You can rollback to v1.21 via https://github.com/Jax-Core/YourMixer/releases/tag/v1.21, or mess with the audio device settings of Windows. Side note, you can change the volume mixer text to Chinese!

**Comment by XiaoYue-Kun** [comment]
I found the problem is probably caused by the Realtek Audio Driver(that's the first device)
My rest programs(including the Device Manager in Control Panel) would recognize it as a microphone instead of a speaker(and indeed it is a microphone) . So it actually cannot be switched to.
When I disable it in the Control Panel, the rest devices can be changed correctly, but in that case the headphone output(the third device) would be disabled as well.
By the way, v1.21 can solve this problem. Thanks.

**Comment by EnhancedJax** [comment]
You might want to disable the first device if you won't be using it

**Comment by XiaoYue-Kun** [comment]
But actually the first and the third device is supported by the same audio driver. If I disable the first, the third would be disabled as well, which means I would lose a microphone and a headphone at the same time.
And the first device is the microphone now I'm using, so it's not quite possible for me to disable it.
Thanks anyway.
