### ISSUE TITLE
Icons of apps I open show up in C:

### ISSUE THREAD

**Issue by ShadowElixir** [Jax-Core/YourMixer#3]
Icons of apps I open show up in C: unless I disable YourMixer, please fix

**Comment by EnhancedJax** [comment]
Reinstall core https://wiki.jaxcore.app/getting-started/faqs

**Comment by joinmod** [comment]
Hi i have same issue but i cant resolve it, even after full reinstall of jaxcore, i still getting png's of active process to the root drive.
is something wrong with fetching icons? and when i open mixer all icons appearing in folder AppIcons at resource/images but still continue fetching to the root drive.
