### ISSUE TITLE
Device selection shows all enabled devices regardless of connection status

### ISSUE THREAD

**Issue by hboyd2003** [Jax-Core/YourMixer#5]
As the title says, the device selection context menu shows all enabled audio output devices no matter if they are connected or not.
This causes frustration when trying to switch devices.

Additionally, I would like to know why a drop down menu has not been implemented? A drop down menu already exists in QuickNote. Could you not adapt that drop down menu to YourMixer?

**Comment by EnhancedJax** [comment]
> As the title says, the device selection context menu shows all enabled audio output devices no matter if they are connected or not.
> This causes frustration when trying to switch devices.

Click on configure device and disabled the ones that won't be used. 

> Additionally, I would like to know why a drop down menu has not been implemented? A drop down menu already exists in QuickNote. Could you not adapt that drop down menu to YourMixer?

Yes. I'll add that to my features-to-add. Thanks for the suggestion

**Comment by Gazzia** [comment]
Hi @EnhancedJax,
Just to add to the second point, it would be a great feature if the currently used device was shown directly from the mixer, as in Window's volume control
![image](https://user-images.githubusercontent.com/36985411/209328573-afaf6434-89fd-41ac-bafa-c2062edcd7e3.png)

Thanks for all the good stuff !

**Comment by EnhancedJax** [comment]
No problem!

>Just to add to the second point, it would be a great feature if the currently used device was shown directly from the mixer, as in Window's volume control

This is certainty possible, but unfortunately I've stepped away from development. Feel free to modify your own copy though!
